### PR TITLE
Fix typo "https://github.com/eclipse-ee4j/jakartaee-tutorial/issues/184"

### PR DESCRIPTION
**Pull request by nehrusingh**
Fixed small type

### CODE REVIEW

**Comment by keilw** [comment]
@nehrusingh What about your ECA? We can't merge this without it in place.

**Comment by keilw** [comment]
@ivargrimstad I am not sure, if the author tried to sign the ECA because merging this is blocked. What about the change, it says "fix typo" but an entire header was removed, does this look OK or not? Since it is just a single change not sure, if the ECA will be resolved any time soon?

**Comment by nehrusingh** [comment]
Please ignore the change. Thank you.

Regards,
-Nehru

**Comment by ivargrimstad** [comment]
Thanks @keilw for checking.
@nehrusingh: I'll close this PR as per your request. Remember to add a signoff to your commits in subsequent PRs.

**Pull request closed without merging**
