### PR TITLE
Remake of computer icon from images

### PR DESCRIPTION
**Pull request by cpusam**
Redraw of the computer icon used for some images of the tutorial.

### CODE REVIEW

**Comment by ggam** [comment]
Looks good!

**Comment by cpusam** [comment]
Ops, it needs some checks from eclipse foundation. I will solve this.

**Comment by keilw** [comment]
Unfortunately @cpusam has no ECA in place, could you please get that done, we cannot merge without.

**Comment by ggam** [comment]
> Ops, it needs some checks from eclipse foundation. I will solve this.

Yes, you'll need to sign the Contributor Agreement (very straightforward process) and amend the commit to sign off it.

**Comment by cpusam** [comment]
Just for information, now ready. Next Saturday I will redraw more images.

**Pull request merged**
