### PR TITLE
Converted to plain AsciiDoc

### PR DESCRIPTION
**Pull request by ggam**
This PR converts the whole tutorial to plain AsciiDoc without JBake. The result can be seen at http://www.ggam.eu/jakartaee-tutorial/

I haven't made any content changes besides removing duplicated titles that weren't needed anymore. To the best of my knowledge, all links and images are still working and this PR is in a mergeable state.

This makes the tutorial easier to maintain and provides a more modern look.

Things I've made:
- Reorganized files in folders. Once the content is updated for Jakarta EE 9, old stuff can be deleted or moved to a "Legacy stuff" category.
- Replaced setext headings with the recommended atx (https://asciidoctor.org/docs/asciidoc-recommended-practices/#section-titles)
- Removed handcrafted tables of contents.
- Enabled syntax highlighting.
- Updating Maven dependencies and cleaning up pom. Now compiles on Java 14.
- Fixed AsciiDoctor warnings and errors. This affected some nested lists.

Closes:
- #187
- #124
- #188
- #190

And makes it straightforward to solve #129.

### CODE REVIEW

**Comment by ggam** [comment]
I know everyone's busy with Jakarta EE 9 work, but could someone please take a look and approve this? I'd like to see this landing to master before continuing work on it.

**Comment by ggam** [comment]
Thanks Ivar! One more approver and we could merge this please?

**Comment by ggam** [comment]
@keilw since you are around, would you please have a look at this?

**Comment by keilw** [comment]
This is really massive, but if it works for you @ggam this looks like the only PR that has no IP problem, so I have a look and might merge it this evening.

**Comment by ggam** [comment]
Thanks @keilw. I'm aware this is a very big PR and I understand the tutorial is noone's priority right now, but this is needed before moving forward.. #193 (draft) only adds some changes on top of this one.

**Comment by ggam** [comment]
Thanks!

**Comment by keilw** [comment]
I saw @ivargrimstad already merged it, thanks.

**Pull request merged**
