### PR TITLE
Jakartee9

### PR DESCRIPTION
**Pull request by DmitriGit**
Hi Hussain,

new version of images are committed. 
I found some errors in figures "56_4", "58_2", "62_1" and "62_2" and will commit them these days.

If you find some errors or suggestions I'll be happy to correct and implement them. 

In any case I'll continue to improve new version of images (found today one improvement) and commit them.

Hope you like my work. :)

Thank you very much,
Dmitri.

### CODE REVIEW

**Comment by ggam** [comment]
This really is a fantastic job. I like it a lot.

Some minor comments:
- There remains some references to Java EE (easily spottable with `find . -type f -name "*svg" | xargs grep "Java EE"`), Jakarta Server Faces (it's now simply Jakarta Faces) and Java Persistence API (Jakarta Persistence) but the rest looks pretty good.
- There are still some png files that I guess are being reworked. In case this is still WIP, would you please make this PR a draft?

And one last topic: the asciidoc obviously will need to be updated to point to the svg files instead of the png ones, but since this PR is dependant on #239 I think it's best to not do it yet, to prevent merge conflicts. I think it's preferable to make a search and replace one #239 is merged.

**Comment by DmitriGit** [comment]
:) I'm glad you like the new version. 
I tried to be as careful as possible, but some mistakes are unavoidable and I'm ready and happy to correct them! :)

There was several peculiarities in creating images (interpreting of text by browser, differences in font when viewed by browser, ecc), creating many images took me a few days, but what matters is the result.
Some "png" are not more used in a new version of EE but was present in previous versions and, for compatibility, I leaved them (detailed description send one of these days). Some "png" (and precisely four images) I'll commit soon. I'll note all your feedback and implement all necessary changes. :)
Thank you, Team! 
Dmitri.


    On Wednesday, March 24, 2021, 08:10:25 PM GMT+1, Guillermo González de Agüero ***@***.***> wrote:  
 
 


This really is a fantastic job. I like it a lot.

Some minor comments:
   
   - There remains some references to Java EE (easily spottable with find . -type f -name "*svg" | xargs grep "Java EE"), Jakarta Server Faces (it's now simply Jakarta Faces) and Java Persistence API (Jakarta Persistence) but the rest looks pretty good.
   - There are still some png files that I guess are being reworked. In case this is still WIP, would you please make this PR a draft?

And one last topic: the asciidoc obviously will need to be updated to point to the svg files instead of the png ones, but since this PR is dependant on #239 I think it's best to not do it yet, to prevent merge conflicts. I think it's preferable to make a search and replace one #239 is merged.

**Review by arjantijms — APPROVED** [review]
I haven't fully looked through the 100s of files, but glanced through them. At a glance this looks absolutely amazing, and I trust the highly knowledgeable people who worked on this.

**Comment by keilw** [comment]
This must not be merged before #250

**Review by keilw — APPROVED** [review]
Seems OK nowm, but please resolve merge conflicts with 8.1 where necessary

**Comment by DmitriGit** [comment]
:) Just for your information Tutorial Team: today finished debates about images format for Specifications (png vs. svg vs. PlantUML vs. other formats) and Kevin Sutter made a decision to use SVG format as official image format:

"@DmitriGit I just replied to the Platform mailing list that I feel that svg images are better than png and I don't want to lose out on your contribution. We can continue debating the pros and cons of the asciidoc images, but as the main maintainer of the Platform doc, I still prefer the svg format."

So my work for "Jakarta EE Tutorial" to convert PNG to SVG was valid and I'm happy for it. :)

Thank you for opportunity to help you. :)

**Comment by bvfalcon** [comment]
> and Kevin Sutter made a decision to use SVG format as official image format

This is a very good news! Text format (not so important - svg, asciidoc or some another) is easier to translate. For example, SVG make possible image translation into russian (https://github.com/bvfalcon/jakarta-ee-tutorial---russian-translation). In Java EE Tutorial it was impossible. I think, localization of documentation is very important factor that reduce entry threshold for beginners

**Pull request merged**
