### PR TITLE
ci: add github actions

### LINKED ISSUE #231: Add a Github  workflow to deploy docs automaticially
Hope to add a GitHub action workflow to automate the deployment to Github pages.

* When Pr is merged in the master to deploy a snapshot version.
* When the repo is tagged with a version, deploy a versioned release via a different URL.

### PR DESCRIPTION
**Pull request by hantsy**
fixes #231

### CODE REVIEW

**Comment by hantsy** [comment]
Signed-off-by: Hantsy Bai <hantsy@gmail.com>

**Comment by ggam** [comment]
Fantastic. Do you know whether project committers will be able to configure the `github.token` o we'll need to request it to webmaster?

**Comment by hantsy** [comment]
@ggam Go to the project Settings, check if possible to set a Secrets there. I think it can be referred as ENV in Github actions command line.

**Comment by ggam** [comment]
I'm not a committer on this repo but hopefully someone with the required permissions can have a look at this.

Btw, is it possible to review this in your fork? Your `gh-pages` branch doesn't have new commits. Also, I think it's better to move the dependabot file to a different PR.

**Comment by hantsy** [comment]
@ggam I tried this PR in my GitHub account. The maven SCM plugin does not work due to permissions issues. I changed to use Github Token and use Github actions to deploy it, it works.

**Comment by ggam** [comment]
Thanks @hantsy I see it updated in your fork. Hopefully @arjantijms @keilw @ivargrimstad can have a look at this? Would love to get this merged.

**Review by ivargrimstad — APPROVED** [review]

**Pull request merged**
