### PR TITLE
Formatting errors fixed

### PR DESCRIPTION
**Pull request by bvfalcon**
Cosmetic fixes: formatting
These commits fixes https://github.com/eclipse-ee4j/jakartaee-tutorial/issues/243 and many other formatting errors

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]

**Comment by keilw** [comment]
@arjantijms Thanks for merging these, is there anything left for [8.1](https://github.com/eclipse-ee4j/jakartaee-tutorial/milestone/1) or could that be tagged, because I don't think anything should be further merged related to Jakarta EE 9 before at least tagging a release with all the changes after the last one? (initial import over 2 years ago)

**Comment by arjantijms** [comment]
@keilw I think 8.1 is done. I just tagged it ;)

The next challenge would now be to get https://github.com/eclipse-ee4j/jakartaee-tutorial/pull/246 merged in.

**Comment by keilw** [comment]
@arjantijms You tagged all the POMs as 8.1-SNAPSHOT, was that the plan or a mistake? As there may not be any deployment to MavenCentral here, I gues it could be acceptable, otherwise please redo without the SNAPSHOT.

**Comment by arjantijms** [comment]
>  was that the plan or a mistake?

Good point, since we don't release to Maven Central (like the samples), I didn't give it much thought tbh. So it was actually neither the plan or a mistake ;)

I'll let it to you then if you'd like to set the poms to 8.1 first, and then re-apply the tag. I'm fine with both.

**Comment by keilw** [comment]
I could do that after checking it out again.

**Pull request merged**
