### PR TITLE
ci: add dependabot config

### PR DESCRIPTION
**Pull request by hantsy**

### CODE REVIEW

**Comment by hantsy** [comment]
@ggam This pr is dependent on Githubactions pr #235

**Comment by pzygielo** [comment]
> @ggam This pr is dependent on Githubactions pr #235

But why? Could it be limited to one separate commit with dependabot config only?

**Comment by hantsy** [comment]
@pzygielo It includes a Github action auto-merge task on the base of PR #235  .

**Comment by pzygielo** [comment]
> @pzygielo It includes a Github action auto-merge task on the base of PR #235 .

I see chain of 5 commits. I don't understand why dependabot config needs 4 of them. If it doesn't - why not include only one commit in this PR, and do not depend on #235?

**Comment by hantsy** [comment]
_See originally posted by @ggam in https://github.com/eclipse-ee4j/jakartaee-tutorial/issues/235#issuecomment-755621715_

This pr is branched based on Pr #235 not master.

**Comment by pzygielo** [comment]
> This pr is branched based on Pr #235 not master.

But why? Would it work without #235?

**Comment by hantsy** [comment]
@pzygielo  So remove this pr?

**Comment by pzygielo** [comment]
I only suppose @ggam meant separate PR like this one - with *only* dependabot configuration file. I imagine https://github.com/eclipse-ee4j/jakartaee-tutorial/pull/237/commits/5c94a18f7efe8b54f5a2957b7460f8ce81a0503f cherry-picked against current master would do.

But I still have not got answer for 
> Would it (with it = #237) work without #235?

> So remove this pr?

I'm no committer here and I only expressed my non-binding opinion on the matter of this request. Its title is _ci: add dependabot config_ and that's what it should do, nothing more.

**Comment by ggam** [comment]
> I only suppose @ggam meant separate PR like this one - with only dependabot configuration file. I imagine 5c94a18 cherry-picked against current master would do.

Indeed, that was the idea :)

**Pull request closed without merging**
